import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./app.css";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <body>
        <Navbar />
        {children}
        <footer>
          <p>© 2024 Physiotherapie Antonio Baptista. Alle Rechte vorbehalten.</p>
        </footer>
      </body>
    </html>
  );
}
