import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./app.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <body>
        <header className="navbar">
          <div className="logo-container">
            <Image
              src="/logo.png"
              alt="Physiotherapie Antonio Baptista Logo"
              width={300} /* Set the desired width */
              height={100} /* Set the desired height */
            />
          </div>
          <h1>Physiotherapie Antonio Baptista</h1>
          <nav>
            <ul>
              <li><Link href="/">Startseite</Link></li>
              <li><Link href="/team">Team</Link></li>
              <li><Link href="/contact">Kontakt</Link></li>
              <li><Link href="/extra">Extra</Link></li>
            </ul>
          </nav>
        </header>
        {children}
        <footer>
          <p>© 2024 Physiotherapie Antonio Baptista. Alle Rechte vorbehalten.</p>
        </footer>
      </body>
    </html>
  );
}
